name: Generate JSON Feeds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate
      run: |
        # Generate the JSON Feeds
        python feed.py \
          -s "${{ vars.CI_PAGES_URL }}" \
          -a "${{ vars.CI_PAGES_URL }}/static/" \
          -b "${{ vars.CI_PAGES_URL }}/feed" \
          -g "${{ secrets.GITHUB_TOKEN }}"
    - name: Copy Static
      run: |
        cp -R html/. static feed/
    - name: Upload Feeds as Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./feed

  # Deployment job
  deploy:
    if: (github.event_name == 'push'
      && github.ref_name == 'main') || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Trigger the front-end to rebuild
  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build Front-end
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: scottstraughan
          repo: sycl.tech-website
          github_token: ${{ secrets.SYCL_TECH_SYNC_TOKEN }}
          workflow_file_name: build.yml
